image: Visual Studio 2015
version: '{branch}.{build}'

cache:
  - c:\build-cache
  - c:\build-cache\sdk -> .appveyor.yml

environment:
  PHP_BUILD_CACHE_BASE_DIR: c:\build-cache
  PHP_BUILD_OBJ_DIR: c:\obj
  PHP_BUILD_CACHE_SDK_DIR: c:\build-cache\sdk
  PHP_BUILD_SDK_BRANCH: php-sdk-2.1.5
  SDK_REMOTE: https://github.com/Microsoft/php-sdk-binary-tools.git
  SDK_BRANCH: php-sdk-2.1.5

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
      PHP_REL: 7.2
      ARCHITECTURES: x86
      ZTS_STATES: enable disable

install:
  - appveyor\install.cmd

build_script:
  - appveyor\build.cmd

artifacts:
  - path: artifacts
    name: php_winbinder.dll
    type: zip
